### PR TITLE
fix: create.sh readable on macos

### PR DESCRIPTION
**Pull request by Samox**

### CODE REVIEW

**Comment by Samox** [comment]
I signed it!

**Comment by chrislovecnm** [comment]
Test this please
Ok to test
/lgtm
/approve

**Comment by chrislovecnm** [comment]
ok to test

**Comment by chrislovecnm** [comment]
test this please

**Comment by chrislovecnm** [comment]
Thanks for your PR, CI is not reporting back.  We will look at that, and get this merged.

**Comment by homernajafi** [comment]
test this please

**Comment by emailbob** [comment]
test this please

**Comment by emailbob** [comment]
test this please

**Comment by emailbob** [comment]
The project in CI is now fixed and is now running in Jenkins

**Pull request merged**
